import {
  Asset,
  Liability,
  IncomeEntry,
  ExpenseEntry,
  CashHolding,
  FinancialMetrics,
  MonthSummaryPoint,
} from '../types/finance'
import { format, subMonths, eachMonthOfInterval } from 'date-fns'

export function calculateFinancialMetrics(
  assets: Asset[] = [],
  liabilities: Liability[] = [],
  incomeEntries: IncomeEntry[] = [],
  expenseEntries: ExpenseEntry[] = [],
  cashHoldings: CashHolding[] = [],
  selectedMonthStr: string // YYYY-MM
): FinancialMetrics {
  // 1. Assets Total
  const totalAssets = assets.reduce(
    (sum, a) => sum + (Number(a.current_value) || 0),
    0
  )

  // 2. Liabilities Total, Good Debt, Bad Debt
  let totalLiabilities = 0
  let goodDebtTotal = 0
  let badDebtTotal = 0

  liabilities.forEach((l) => {
    const outstanding = Number(l.outstanding_amount) || 0
    totalLiabilities += outstanding
    if (l.is_good_debt) {
      goodDebtTotal += outstanding
    } else {
      badDebtTotal += outstanding
    }
  })

  const goodDebtPercentage =
    totalLiabilities > 0 ? (goodDebtTotal / totalLiabilities) * 100 : 0
  const badDebtPercentage =
    totalLiabilities > 0 ? (badDebtTotal / totalLiabilities) * 100 : 0

  // 3. Liquid Cash for the selected month (or latest available)
  const currentMonthCashEntry = cashHoldings.find((c) =>
    c.month.startsWith(selectedMonthStr)
  )
  const liquidCash = currentMonthCashEntry
    ? Number(currentMonthCashEntry.amount) || 0
    : 0

  // 4. Net Worth = Total Assets - Total Liabilities + Liquid Cash
  const netWorth = totalAssets - totalLiabilities + liquidCash

  // 5. Month Income: Active & Passive
  // Note: Assets that generate monthly income (like rental property / dividend stocks)
  // automatically contribute to passive income if not logged separately as entries
  const monthIncomes = incomeEntries.filter((i) =>
    i.month.startsWith(selectedMonthStr)
  )

  const activeIncome = monthIncomes
    .filter((i) => i.type === 'active')
    .reduce((sum, i) => sum + (Number(i.amount) || 0), 0)

  const loggedPassiveIncome = monthIncomes
    .filter((i) => i.type === 'passive')
    .reduce((sum, i) => sum + (Number(i.amount) || 0), 0)

  // Monthly passive income generated by owned assets
  const assetPassiveIncome = assets.reduce(
    (sum, a) => sum + (Number(a.monthly_income_generated) || 0),
    0
  )

  const passiveIncome = loggedPassiveIncome + assetPassiveIncome
  const totalIncome = activeIncome + passiveIncome

  // 6. Month Expenses breakdown
  const monthExpenses = expenseEntries.filter((e) =>
    e.month.startsWith(selectedMonthStr)
  )

  const needsExpenses = monthExpenses
    .filter((e) => e.category === 'needs')
    .reduce((sum, e) => sum + (Number(e.amount) || 0), 0)

  const wantsExpenses = monthExpenses
    .filter((e) => e.category === 'wants')
    .reduce((sum, e) => sum + (Number(e.amount) || 0), 0)

  const emiExpenses = monthExpenses
    .filter((e) => e.category === 'emi_payments')
    .reduce((sum, e) => sum + (Number(e.amount) || 0), 0)

  const otherExpenses = monthExpenses
    .filter((e) => e.category === 'other')
    .reduce((sum, e) => sum + (Number(e.amount) || 0), 0)

  const totalExpenses =
    needsExpenses + wantsExpenses + emiExpenses + otherExpenses

  // 7. Core Rich Dad Metric: Passive Income Gap & Rat Race Status
  const passiveIncomeGap = passiveIncome - totalExpenses
  const isFinanciallyFree = passiveIncome >= totalExpenses && totalExpenses > 0
  const freedomRatio =
    totalExpenses > 0 ? (passiveIncome / totalExpenses) * 100 : passiveIncome > 0 ? 100 : 0

  const netMonthlyCashflow = totalIncome - totalExpenses
  const savingsRate =
    totalIncome > 0 ? ((totalIncome - totalExpenses) / totalIncome) * 100 : 0
  const debtToAssetRatio =
    totalAssets > 0 ? (totalLiabilities / totalAssets) * 100 : 0

  return {
    totalAssets,
    totalLiabilities,
    netWorth,
    liquidCash,
    activeIncome,
    passiveIncome,
    totalIncome,
    needsExpenses,
    wantsExpenses,
    emiExpenses,
    otherExpenses,
    totalExpenses,
    netMonthlyCashflow,
    passiveIncomeGap,
    freedomRatio,
    isFinanciallyFree,
    goodDebtTotal,
    badDebtTotal,
    goodDebtPercentage,
    badDebtPercentage,
    debtToAssetRatio,
    savingsRate,
  }
}

/**
 * Computes historical / trend data points for the "Escaping the Rat Race" dual-line chart
 */
export function calculateMonthlyTrends(
  assets: Asset[] = [],
  incomeEntries: IncomeEntry[] = [],
  expenseEntries: ExpenseEntry[] = [],
  monthsCount: number = 6,
  endMonthDate: Date = new Date()
): MonthSummaryPoint[] {
  const validEndDate = endMonthDate instanceof Date && !isNaN(endMonthDate.getTime())
    ? endMonthDate
    : new Date()
  const startDate = subMonths(validEndDate, Math.max(1, monthsCount) - 1)
  const monthInterval = eachMonthOfInterval({ start: startDate, end: validEndDate })

  const assetPassiveBase = assets.reduce(
    (sum, a) => sum + (Number(a.monthly_income_generated) || 0),
    0
  )

  return monthInterval.map((date) => {
    const monthKey = format(date, 'yyyy-MM')
    const displayMonth = format(date, "MMM ''yy")

    // Filter incomes for month
    const mIncomes = incomeEntries.filter((i) => i.month.startsWith(monthKey))
    const mExpenses = expenseEntries.filter((e) => e.month.startsWith(monthKey))

    const active = mIncomes
      .filter((i) => i.type === 'active')
      .reduce((sum, i) => sum + (Number(i.amount) || 0), 0)

    const passive =
      mIncomes
        .filter((i) => i.type === 'passive')
        .reduce((sum, i) => sum + (Number(i.amount) || 0), 0) +
      assetPassiveBase

    const expenses = mExpenses.reduce(
      (sum, e) => sum + (Number(e.amount) || 0),
      0
    )

    const netCashflow = active + passive - expenses
    const gap = passive - expenses
    const isFree = passive >= expenses && expenses > 0

    return {
      month: monthKey,
      displayMonth,
      passiveIncome: passive,
      totalExpenses: expenses,
      activeIncome: active,
      netCashflow,
      isFree,
      gap,
    }
  })
}
